
/// Test för att hämta alla användare ///
GET http://localhost:3000/login

###

/// Test-post med rätt email och lösenord ///
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "tets@email.com",
    "password": "testPassword"
}

###

/// Test-post med fel email och lösenord ///
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "carolien@hagg.com",
    "password": "ägg"
}


###

/// Post för att lägga till en användare ///
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Test person",
    "email": "tets@email.com",
    "password": "testPassword",
    "subOnNewsletter": true
}


###

/// Post för att lägga till en användare ///
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Caroline hägg",
    "email": "carolien@hagg.com",
    "password": "hägg",
    "subOnNewsletter": true
}