
/// Test för att hämta alla användare ///
GET http://localhost:3000/login

###

/// Test-post med rätt email och lösenord ///
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "tets@email.com",
    "password": "testPassword"
}

###

/// Test-post med fel email och lösenord ///
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "caroline@hagg.com",
    "password": "ägg"
}


###

/// Post för att lägga till en användare ///
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Test person",
    "email": "tets@email.com",
    "password": "testPassword",
    "subOnNewsletter": true
}


###

/// Post för att lägga till en användare ///
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Caroline hägg",
    "email": "caroline@hagg.com",
    "password": "hägg",
    "subOnNewsletter": false
}


###


PUT http://localhost:3000/register
Content-Type: application/json

{
    "_id": "628f7e73992cb8e1dc692237",
    "subOnNewsletter": false
}


###


/// PUT för att ändra i en användare ///
PUT http://localhost:3000/register
Content-Type: application/json

{
    "_id": "628f7e66992cb8e1dc692234",
    "subOnNewsletter": true
}